version: "3"

services:
  ansible-control:
    build: ./centos-ansible/.
    command: /bin/bash
    tty: true
    stdin_open: true
    networks:
      - back-tier
  
  web1:
    build: ./centos/.
    tty: true
    stdin_open: true
    ports:
      - "81:80"
    networks:
      - back-tier

  web2:
    build: ./centos/.
    tty: true
    stdin_open: true
    ports:
      - "82:80"
    networks:
      - back-tier

  mysqldb1:
    build: ./centos/.
    tty: true
    stdin_open: true
    ports:
      - "1433:1433"
    networks:
      - back-tier

networks:
  back-tier:
